print('Most már látod?')
print("Elvileg lááátom!")
print('Ez tök jóságos :D')
print("Valóban tök jóságos, csak rövid :D")
print('Azt is látod ahova kattintgatok?')
print("Nyim, azt nyim játom.")
print('Mindegy, elvileg oldalt ott van a commit fül ha bejelentkeztél git-re')
print("Valami van. Csak ez don't az én cuccom, szóval nehezen igazodom el.")
print('Saját cuccod nincsen?')
print("Ez volt hirtelen kényelmesebb. :D (...) Mert nem jelentkeztem be :D")
print('Fent a windows meg a tools között ott a VCS fül, ott kell engedélyenzni a verziókezelést')
print("Én ezt gyűlölöm. Nézem.")
print('Amúgy nem kell fizetni érte, csak félóránként újraindítani :D')
print('Áháá... közben felpurcikáztam egy saját repo-ba azt a mocskot.')
print('Akkor hívj be a repoba mint collaborator :D')
print("Rajta vagyok. Az már megvan, hogy hol kell.")
print('Szupcsi. A végén még menni fog ez :D')
print("Elvilegséges bennevagyságoltalak. :D")
print('El vagyon fogadva :)')
print("Nekem ez abszolút üres. Vagy csak nem tudom hol vannak benne a cuccok.")
print('Ez tök üres :)')
print("De hiszen felnyomtam. Szítszedem ezt a hülyesíget...")
print('Biztos, hogy ebbe?')
print("Biztos.")
print("Nem mintha lenne EGYÁLTALÁN lehetőség bármin vbáltoztatni. Vagy push, vagy nem push, de csak egy opció van.")
print('GIT -> Manage Remote ott megadod ezt az elérési utat, és akkor ezt a repot fogja használni https://github.com/Lisaa01/Web.git')
print("Pontosan ez van ott.")
print('És commitoltál push előtt?')
print("IGen. Vagy legalábbis rányomtam. Hogy az elég-e, vagy kell más is, azt nem tudom.")
print('A commitnál kell megadni valami szöveget az alsó boxba és ki kell választani a fájlokat különben magától nem tudja mit akarsz')
print('Írtam szöveget, ki vannak pipáávaaa, csapkodom a commitot de semmi sem váááltozik.')
print('A projekt nézetben ahol a fájlok látszanak ott pirosak a neveik?')
print("Ződek")
print('Akkor próbád meg a push gombot nyomkodni :D')
print("Asztis nyomkodom már egy ideje, de szaaaar...")
print('Már ez amit itt írkálunk ott van')
print("Látogatom, de nekem bacódik működni ez a mocsokszar")
print('A git -> branches-hez írtam be ugyan azt a linket')
print("Nekem nem enged oda beírni semmiit.")
print('Van benne olyan hogy new branch')
print("Szürke. Nem kattintható.")
print('Akkor most hogy ez fent van próbáld meg lehúzni')
print("Asszongya master has no tracked branch")
print('Mert nem master a branch name')
print("És azzal mit csináljak?")
print('Fent a git fül new branch')
print("Local Braches  master  Nem jó?")
print('Nem mert ugyan abba a branchbe akarja feltölteni is')
print("So? [Mellékesen megjegyzem, hogy ez a legszarabb szofteres, online plaftormos szar, amit valaha láttam.]")
print('Csináltam neked master branchet')
print("Tiszta ügyes vagy, és ez mire lesz jó? Most se jó a push. DE legalább kiírna egy kurva hibát, vagy bármi...")
print('Ha a commit fül van megnyitva mit ír fölül?')
print("Commit to master")
print('A saját gitedbe vagy bejelentkezve?')
